companieshouse/accounts-user-api

src/main/java/uk/gov/companieshouse/accounts/user/controller/GetUserRecordController.java, src/main/java/uk/gov/companieshouse/accounts/user/repositories/UsersRepository.java, src/main/java/uk/gov/companieshouse/accounts/user/service/UsersService.java, src/test/java/uk/gov/companieshouse/accounts/user/controller/GetUserRecordControllerTest.java, src/test/java/uk/gov/companieshouse/accounts/user/integration/GetUserRecordControllerTest.java, src/test/java/uk/gov/companieshouse/accounts/user/integration/UsersServiceTest.java, src/test/java/uk/gov/companieshouse/accounts/user/repositories/UsersRepositoryTest.java, src/test/java/uk/gov/companieshouse/accounts/user/service/UsersServiceTest.java
New endpoint to fetch user details for a given userId
IDVA6 507
=> Idva6 507 fetch user for user

terraform/groups/ecs-service/locals.tf
=> modifying health path

pom.xml
Updated pom.xml to import the new email regex.
IDVA6-552
=> Updated the email regex

src/test/java/uk/gov/companieshouse/accounts/user/integration/UserRolesControllerTest.java
=> Refactoring the code to resolve Integration coverage error

src/main/java/uk/gov/companieshouse/accounts/user/service/UsersService.java
=> fix sonar critical issues

pom.xml, src/main/java/uk/gov/companieshouse/accounts/user/configuration/InterceptorConfig.java, src/main/java/uk/gov/companieshouse/accounts/user/interceptor/EricAuthorisedKeyPrivilegesInterceptor.java
Added support for privilege key.
IDVA6-673
=> Added support for privilege key.

README.md, docs/common-api-libraries-readme.md
=> Links update

terraform/groups/ecs-service/locals.tf
=> fix: added the missing quote

pom.xml
=> UserAPI regex update

terraform/groups/ecs-service/locals.tf
=> fix: added the interface to terraform to make it accessible

pom.xml, src/main/java/uk/gov/companieshouse/accounts/user/service/RolesService.java, src/test/java/uk/gov/companieshouse/accounts/user/controller/RolesControllerTest.java, src/test/java/uk/gov/companieshouse/accounts/user/integration/RolesControllerTestIntegratrion.java
=> feat: Updated to use the latest private-api-sdk-java

pom.xml
=> IDVA6-1227: Update to Spring Boot 3.3

src/main/java/uk/gov/companieshouse/accounts/user/interceptor/EricAuthorisedKeyPrivilegesInterceptor.java
=> test: temporary log message to help highlight issue

src/main/java/uk/gov/companieshouse/accounts/user/interceptor/EricAuthorisedKeyPrivilegesInterceptor.java
=> revert: removed fault finding log message

terraform/groups/ecs-service/data.tf
Migrate load balancer from internal to accounts
=> change lb from internal to accounts

terraform/groups/ecs-service/locals.tf
=> Making changes to the Account users api

pom.xml
bump up parent pom to the latest one to use new sonar plugin
=> bump up parent pom to the latest one to use new sonar plugin

pom.xml, src/main/java/uk/gov/companieshouse/accounts/user/configuration/InterceptorConfig.java, src/main/java/uk/gov/companieshouse/accounts/user/controller/RolesController.java, src/main/java/uk/gov/companieshouse/accounts/user/interceptor/EricAuthorisedKeyPrivilegesInterceptor.java, src/test/java/uk/gov/companieshouse/accounts/user/controller/RolesControllerTest.java, src/test/java/uk/gov/companieshouse/accounts/user/integration/RolesControllerTestIntegratrion.java, src/test/java/uk/gov/companieshouse/accounts/user/interceptor/InterceptorTests.java
=> feat: updated to use latest version of private-api-sdjk-java

terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
=> Update vars to use staging

pom.xml, src/main/java/uk/gov/companieshouse/accounts/user/configuration/MongoConfig.java, src/main/java/uk/gov/companieshouse/accounts/user/controller/RolesController.java, src/main/java/uk/gov/companieshouse/accounts/user/mapper/DateTimeMapper.java, src/main/java/uk/gov/companieshouse/accounts/user/mapper/UsersDtoDaoMapper.java, src/test/java/uk/gov/companieshouse/accounts/user/controller/RolesControllerTest.java, src/test/java/uk/gov/companieshouse/accounts/user/integration/FindUserBasedOnEmailControllerTest.java, src/test/java/uk/gov/companieshouse/accounts/user/integration/FindUsersBasedOnPartialEmailControllerTest.java, src/test/java/uk/gov/companieshouse/accounts/user/integration/GetUserRecordControllerTest.java, src/test/java/uk/gov/companieshouse/accounts/user/integration/RolesControllerTestIntegratrion.java, src/test/java/uk/gov/companieshouse/accounts/user/interceptor/InterceptorTests.java
allows for a role to be created without any permissions
CC-1500
=> fix: updated to handle the `created` field

terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars
=> live endpoints for oauth and perl rewrite release

terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars, terraform/groups/ecs-service/profiles/development-eu-west-2/phoenix1/vars, terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars, terraform/groups/ecs-service/variables.tf
Add /user/profile to lb_listener_paths for phoenix1, cidev & staging
IDVA6-1317
=> IDVA6-1317 Enable user-profile endpoint

src/main/java/uk/gov/companieshouse/accounts/user/controller/GetUserRecordController.java, src/test/java/uk/gov/companieshouse/accounts/user/controller/UserProfileTest.java
Adding a new field in the getUserProfile method which adds  token_permissions to user profile. This works locally on CHS Docker with branch `feature/beta-phase-dev/ci`
[IDVA2-804](https://companieshouse.atlassian.net/browse/IDVA2-804)
[IDVA2-804]: https://companieshouse.atlassian.net/browse/IDVA2-804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> add token_permissions to user profile

terraform/groups/ecs-service/profiles/development-eu-west-2/phoenix1/vars
=> IDVA6-1317 add specific /user/profile endpoint for phoenix1

terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars, terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
=> IDVA6-1317 add /user/profile endpoint to cidev and staging

terraform/groups/ecs-service/main.tf, terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars, terraform/groups/ecs-service/profiles/development-eu-west-2/phoenix1/vars, terraform/groups/ecs-service/variables.tf
=> add scaledown to cidev/phoenix and update modules

terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars
Switches on user/profile in live to match it being removed from authentication-service
=> Move user profile get to accounts-user

terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars
set live endpoints for private beta
IDVA6-1566
=> IDVA6-1566 set live endpoints for private beta

terraform/groups/ecs-service/profiles/live-eu-west-2/livesbox/vars, terraform/groups/ecs-service/profiles/staging-eu-west-2/stagsbox/vars
=> Add sandbox envs

terraform/groups/ecs-service/profiles/development-eu-west-2/rebel1/vars
=> Add rebel1 vars

src/test/java/uk/gov/companieshouse/accounts/user/integration/FindRolesBasedOnUserIDControllerTest.java, src/test/java/uk/gov/companieshouse/accounts/user/integration/FindUserBasedOnEmailControllerTest.java, src/test/java/uk/gov/companieshouse/accounts/user/integration/FindUsersBasedOnPartialEmailControllerTest.java, src/test/java/uk/gov/companieshouse/accounts/user/integration/GetUserRecordControllerTest.java, src/test/java/uk/gov/companieshouse/accounts/user/integration/OneloginControllerTest.java, src/test/java/uk/gov/companieshouse/accounts/user/integration/RolesControllerTestIntegratrion.java, src/test/java/uk/gov/companieshouse/accounts/user/integration/UserRolesControllerTest.java, src/test/java/uk/gov/companieshouse/accounts/user/integration/UserRolesServiceTest.java, src/test/java/uk/gov/companieshouse/accounts/user/integration/UsersServiceTest.java, src/test/java/uk/gov/companieshouse/accounts/user/interceptor/InterceptorTests.java, src/test/java/uk/gov/companieshouse/accounts/user/repositories/UsersRepositoryTest.java
Integration tests were failing in pipeline. Fixed.
IDVA6-1936
=> IDVA6-1936: Fixed tests

pom.xml, src/test/java/uk/gov/companieshouse/accounts/user/controller/UserRolesControllerTest.java, src/test/java/uk/gov/companieshouse/accounts/user/integration/FindRolesBasedOnUserIDControllerTest.java, src/test/java/uk/gov/companieshouse/accounts/user/integration/FindUserBasedOnEmailControllerTest.java, src/test/java/uk/gov/companieshouse/accounts/user/integration/FindUsersBasedOnPartialEmailControllerTest.java, src/test/java/uk/gov/companieshouse/accounts/user/integration/GetUserRecordControllerTest.java, src/test/java/uk/gov/companieshouse/accounts/user/integration/OneloginControllerTest.java, src/test/java/uk/gov/companieshouse/accounts/user/integration/RolesControllerTestIntegratrion.java, src/test/java/uk/gov/companieshouse/accounts/user/integration/UserRolesControllerTest.java, src/test/java/uk/gov/companieshouse/accounts/user/integration/UserRolesServiceTest.java, src/test/java/uk/gov/companieshouse/accounts/user/integration/UsersServiceTest.java, src/test/java/uk/gov/companieshouse/accounts/user/interceptor/InterceptorTests.java, src/test/java/uk/gov/companieshouse/accounts/user/repositories/UsersRepositoryTest.java, src/test/resources/application.properties
Swapped Testcontainers for Flapdoodle.
IDVA6-1925
=> IDVA6-1925: Swapped Testcontainers for Flapdoodle.

pom.xml
Upgraded Spring to the latest version, and addressed security failures.
IDVA6-1925
=> IDVA6-1925: Upgraded spring

terraform/groups/ecs-service/profiles/development-eu-west-2/titans1/vars
adding titans1 env 
* [x ] Infrastructure change
=> add titans1 env to service

terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars, terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
=> MODIFYING THE SCALING THEASHOLD

terraform/groups/ecs-service/main.tf, terraform/groups/ecs-service/variables.tf
=> ADDING THE MIN TASKS COUNT TO THE VARIABLE AND MAIN FILE
